export const reset = "\x1b[0m"
export const bright = "\x1b[1m"
export const dim = "\x1b[2m"
export const underscore = "\x1b[4m"
export const blink = "\x1b[5m"
export const reverse = "\x1b[7m"
export const hidden = "\x1b[8m"

export const fgblack = "\x1b[30m"
export const fgred = "\x1b[31m"
export const fggreen = "\x1b[32m"
export const fgyellow = "\x1b[33m"
export const fgblue = "\x1b[34m"
export const fgmagenta = "\x1b[35m"
export const fgcyan = "\x1b[36m"
export const fgwhite = "\x1b[37m"

export const bgblack = "\x1b[40m"
export const bgred = "\x1b[41m"
export const bggreen = "\x1b[42m"
export const bgyellow = "\x1b[43m"
export const bgblue = "\x1b[44m"
export const bgmagenta = "\x1b[45m"
export const bgcyan = "\x1b[46m"
export const bgwhite = "\x1b[47m"